redox-os/ion

src/lib.rs
Use the result information to catch bad commands before running them
=> Avoid using _unused

src/main.rs
Environment variables and commands are now stored in maps. This simplifies the code and makes it more efficient. In the future we should switch to HashMaps, but BTreeMaps will do just fine for now.
=> Switch to maps for variables and commands

src/expansion.rs, src/main.rs, src/parser.rs, src/tokenizer.rs
=> Handle multiple commands per line; move toward a parser

src/main.rs
It is essentially the same as "touch acpi:off"
=> "poweroff" command

src/expansion.rs, src/input_editor.rs, src/main.rs, src/parser.rs, src/to_num.rs, src/tokenizer.rs
Line comment anything that needs fixing
=> run rustfmt on ion

src/main.rs
Remove our flavor of `exec` command and make the shell do what it did by
default. Unlike a normal exec command, ours just forked a child like a
normal shell does when you supply a non-builtin command. Now Ion does
this.
If you have the program exa on your path, then you can just type `exa`
and it will work on Linux.
=> Make current `exec` default action

src/builtin.rs, src/expansion.rs, src/input_editor.rs, src/main.rs
This change should make it possible to test builtins easier. Furthermore builtin functions now have function signatures that reflect how they actually operate.
=> Move builtins to their own module

SYNTAX.md
I'm not sure the executable path thing is correct.
=> Minor fixes

Cargo.toml
Anyone else who contributes is welcome to put themselves in Cargo.toml
as well.
=> Move myself to first author as tikci suggested

src/main.rs
Update documentation, get rid of useless stuff, run `cargo fmt`
=> Minor cleanups

src/variables.rs
=> Add unit tests for variables

src/history.rs, src/main.rs
This patch also fixes an off by one error in the history size.
=> Move history to its own module

src/builtin.rs, src/directory_stack.rs, src/history.rs, src/main.rs, src/peg.rs, src/variables.rs
The results are somewhat mixed, but I think this is an improvement.
=> Try to fix the usage of Strings

src/main.rs, src/peg.rs, src/variables.rs
It is pretty pointless right now, but it is a start.
=> Add backgrounding

SYNTAX.md
I didn't update the proposed grammar. Since it is rough and incomplete, I didn't want to take the time to maintain it. If I or someone else does an overhaul at some point, that would be great.
=> Remove curly braces from purposed syntax

src/main.rs
The following changes will allow ion to evaluate an init file in the user's home directory, such as **/home/mmstick/.ionrc**. In addition, I've also added the capability to use the `source` command which will either read from a defined file argument as input or re-read the init file. Hopefully you won't mind,  but I've also cleaned up the last bit of code at the end of the main function so that it's a `while let` loop instead of a `loop` loop.
=> Implement Init and `source` Command

src/flow_control.rs, src/function.rs, src/main.rs, src/peg.rs
Current syntax:
```
fn function_name
echo "Hello, World"
end
function_name
> Hello, World
```
It works, but I feel that my code is quite bad (lots of `clone()` for example) so if you have any comments don't hesitate to tell me.       
Also, the `if...end` and `for...end` blocks don't work inside a function, so for now they are just aliases (but I'm going to try to fix this)
=> Added functions without arguments

src/main.rs
It may not be the smartest way to do this, but it is simple and it works. Fixes #108
=> Add dash c

src/variables.rs
=> Escape string expansion with backslash / Fix #125

src/main.rs
=> Add the PROMPT variable

src/variables.rs
=> Check the validity of the variable name

Cargo.toml, SYNTAX.md, src/main.rs, src/peg.rs, src/pipe.rs, src/variables.rs
I removed backgrounding for now because it allowed me to clean things up a lot and not have to deal with adding support for it to pipelines at the moment. I am opening several issues that this patch does not address.
=> Redirection

src/main.rs
Now all we need is to alias ~ to $HOME, which I'm not sure how to do right now.
=> Add HOME Variable

src/main.rs
This should provide the noop capabilities without needing to spawn a new process to do it.
=> Add Built-in True and False

src/main.rs
I'm not sure if you have already taken a decision. Anyway, if you want to change the variable name from `CWD` to `PWD` you can merge this, otherwise you can just close this PR.
Fixes #146
=> Use PWD variable instead of CWD

src/main.rs, src/peg.rs, src/pipe.rs, src/variables.rs
=> Show message when command is not found + some refactoring

Cargo.toml, src/main.rs, src/variables.rs
This adds tilde expansion with the following options like in bash `~`,
`~+`, and `~-`.
=> Add tilde expansion

src/main.rs
This will add the OLDPWD variable which is currently missing. It will also only update the PWD and OLDPWD variables when the program detects that the current working directory has changed.
=> Add OLDPWD Variable

src/peg.rs, src/pipe.rs, src/variables.rs
=> >> now appends to the file

.github/ISSUE_TEMPLATE, .github/PULL_REQUEST_TEMPLATE
Maybe we should wait a bit so everyone who have arguments for/against the templates can participate in the discussion.
I copied the templates from redox-os/redox#567
Fixes #163
=> Add issue and PR templates

src/main.rs, src/variables.rs
Unlet isn't a real word, so it feels weird to use it to delete variables.
=> Use drop instead of unlet

src/peg.rs
- [...]
- [...]
- [...]
**Drawbacks**: [if any, describe the drawbacks of this pull request.]
**Blocking/related**: [issues or PRs blocking or being related to this issue.]
**Other**: [optional: for other relevant information that should be known or cannot be described in the other fields.]
------
_The above template is not necessary for smaller PRs._
=> Fixed error message on bad syntax

SYNTAX.md
=> Correct SYNTAX.md for unsetting variable

src/peg.rs
Fix a bunch of `error: variable does not need to be mutable`
=> fix tests in peg.rs

src/to_num.rs
Just a small style thing.
The constants defined in `status.rs` have also caught my attention. I'd have to look more closely at exactly how they are used to be sure, but it looks to me like they could be replaced by some kind of `enum`.
=> Use match rather than if/else if

src/shell_expand/mod.rs, src/shell_expand/variables.rs, src/shell_expand/words.rs, src/variables.rs
Expand `$(command args)` by calling a subshell
=> Process expansion

Cargo.lock, examples/run_examples.sh, src/main.rs, src/variables.rs
**Problem**:
- Ion does not load a history file
- Default values are being set in an ad-hoc manner rather than implementing the Default trait.
- Some of the documentation wording is awkward.
- Some functions are imported without keeping their module name.
- Ion does not track the execution time of the commands it runs.
I can add more to this. I just want to get it out since I wrote it a while ago now.
=> Clean up and test summary

src/peg.rs
Fixed an issue from the last pull request and added test units for the following two cases:
```
let A = "$(seq 1 10)"; echo $A; echo "$A"
```
```
let A = $(seq 1 10); echo $A; echo "$A"
```
=> Fix Last Pull Request

src/main.rs, src/variables.rs
Implements support for creating aliases, resolving issue #215. I've implemented the syntax to utilize the existing `let` keyword, like so:
```sh
let alias ls = "ls --color"
ls -l
```
=> Implement Aliasing Support

src/directory_stack.rs, src/main.rs, src/parser/shell_expand/variables.rs, src/pipe.rs
- Errors are now written to standard error instead of standard out
- Command history is now available as completions for liner
- Fixed variables in single quotes being expanded in subshells
=> Write Errors to Stderr & History Completion

src/flow_control.rs, src/main.rs, src/parser/grammar.rustpeg, src/parser/loops/for_grammar.rs, src/parser/loops/mod.rs, src/parser/loops/while_grammar.rs, src/parser/mod.rs
The current implementation is simple in that it will parse the expression for each loop and check if the value is either **true** or **1**. I plan to give it the ability to perform conditional expressions of it's own later when I have more time.
It doesn't have to be merged now if you'd prefer to wait for the conditional expressions support.
=> Implement While Support

src/shell/mod.rs
This implements script arguments $0, $1, etc.
It also implements bash-compatible syntax for -c, where the first argument is a command string and the later arguments are arguments $0 and on.
Example of -c:
`ion -c "echo $0 $1 $2 $3" a b c d`
Output:
```
a b c d
```
Example of script:
```
#test.ion
echo $0 $1 $2 $3
```
`ion test.ion a b c d`
Output:
```
test.ion a b c d
```
=> Add script arguments, implement -c similarly to bash

Cargo.toml, src/builtins/echo.rs, src/builtins/mod.rs, src/shell/job.rs, src/shell/mod.rs
**Problem**: Adding coreutils/echo as a ion builtin command
**Solution**: I have added the full coreutils/echo source code as a builtin command and changed it slightly to work with ion API
- Added coreutils as a dependency to make use of ArgParser
- Added a new echo.rs to src/builtins containing the echo functionality
- Added a command at src/builtins/mod.rs to call the new echo function
- Added echo command to src/shell/job.rs making it possible to pipeline
=> Echo builtin

src/builtins/calc.rs
Like requested in my previous PR.
I haven't added XOR, >> or << (because I would have to change the way tokens get parsed, since they are single characters now).
=> Added some requested calculations methods

src/shell/job.rs
=> Empty argument slice now results in empty command

README.md
See #375; until that issue is resolved we ought to have our examples do sensible things.
=> Change example in README to reflect tilde expansion rules

src/parser/shell_expand/words.rs
See comments in https://github.com/redox-os/ion/issues/375.
=> Tilde now properly expands inside a normal word

src/parser/shell_expand/mod.rs, src/parser/shell_expand/words.rs
**Fixes**: Closes #406.
**Summary**: Instead of parsing tildes separately from normal tokes they are now included inside normal tokens, but the `tilde` flag is set so when they are expanded the `ExpansionFunction::tilde` function is called on the string.
- Very untested (but all the tests pass, and the examples)
- I'm not sure this is the optimal solution, but it works
- This is dependent on `expand_func.tilde` expecting a full path that is prefixed with a tilde; I'm not sure if we're ok with that.
=> Tildes are now part of normal tokens

src/builtins/mod.rs
There are two changes in here.
1) I noticed `unalias` was at some point accidentally defined as a `drop` so we had `drop` down twice.
2) The closure method made it a little more difficult than it needed to be to see what errored with RUST_BACKTRACE=1 and to set breakpoints in a debugger. Now instead of `{{closure}}` you'll get the actual function.
=> Making the builtins a little neater. Closures weren't very friendly for debuggers/backtrace

examples/braces.ion, examples/braces.out, src/parser/shell_expand/ranges.rs
=> Fix for range syntax bugs

src/parser/shell_expand/words.rs
Add a few more string methods. $reverse by graphemes, $to_lowercase and $to_uppercase by whole string.
=> Add reverse, to_lowercase, to_uppercase

src/builtins/mod.rs, src/builtins/variables.rs, src/shell/variables.rs
=> Add option to drop builtin for dropping arrays

src/shell/directory_stack.rs
=> implemented popd command line options

src/shell/binary.rs, src/shell/history.rs, src/shell/variables.rs
=> Switch from HISTORY_FILE to HISTFILE

src/shell/directory_stack.rs
=> Implemented command line options to pushd, dirs.

src/parser/statement/splitter.rs
**Fixes**: Closes #491 
---
I feel really silly for missing this before.
=> Remove POST_MATHEXPR flag when encountered

src/shell/variables.rs
=> Fix syntax error in src/shell/variables.rs

Cargo.toml, src/builtins/calc.rs
Added reverse polish notation support to inbuilt valc command
=> Add polish notation 

README.md
Removed just some stray words.
=> Fix small error in readme

src/shell/assignments.rs
The ability to ignore commands was removed in `6308880f6a` without any explanation why and the Documentation still refers to this feature so this PR bring it back.
=> re-enable ignoring commands in history

src/shell/plugins/methods/unix.rs, src/shell/plugins/namespaces/unix.rs
Treating `c_char` and `i8` as interchangeable makes program less portable since these types are defined differently per-platform.
Use the `c_char` alias whenever applicable instead of `i8`.  
Find and fix other such problems with types used without aliases and maybe switch to higher-lever wrapper libraries to prevent such issues altogether.
=> use `c_char` for plugin arguments instead of `i8`

examples/methods.ion, examples/methods.out, src/parser/shell_expand/words/methods/strings.rs
Issue  #441, implement string method regex_replace().
=> Implement $regex_replace

src/shell/mod.rs
=> Add a get_array() method to the public API.

manual/src/ch11-00-builtins.md
=> Documented Builtins

.cargo/config, .gitignore, .travis.yml, .travis/redox-toolchain.sh
I've been meaning to do this, but only recently took the time to install a Debian chroot and figure out an issue that was interfering with it (https://github.com/redox-os/libc/pull/43).
I've sent a similar PR to uutils: https://github.com/uutils/coreutils/pull/1095
=> Build for Redox on Travis

manual/src/ch03-05-multicomments.md
**Fixes**: code highlighting and indentation in the documentation for multi-line comments.
**State**: Ready.
------
**Before**:
**After**:
=> Add code block for multi-line comments in the docs.

manual/src/ch05-05-method.md, src/parser/shell_expand/words/methods/strings.rs
Update the documentation and add a couple missing tests.
=> Update documentation of string methods.

Cargo.lock, Cargo.toml, src/lib.rs, src/main.rs, src/shell/mod.rs, src/shell/plugins/mod.rs, src/shell/variables/mod.rs
=> Migrate to xdg

manual/src/ch07-01-conditionals.md, src/builtins/echo.rs, src/builtins/exists.rs, src/builtins/is.rs, src/builtins/job_control.rs, src/builtins/man_pages.rs, src/builtins/mod.rs, src/builtins/set.rs, src/builtins/status.rs, src/builtins/test.rs
Added manpages for lots of builtins and put manpage specific functionality into a new module.
=> Add manpages for almost all builtins.

src/parser/shell_expand/ranges.rs, src/shell/binary/prompt.rs, src/shell/pipe_exec/command_not_found.rs, src/shell/pipe_exec/mod.rs
=> Command not found hook

src/parser/pipelines/collector.rs
This fixes the panic on #552.
It's not the final solution, as the logic is still flawed in some cases, but will solve immediate, more urgent problem.
=> Fix panic on heredoc

src/parser/pipelines/collector.rs, src/parser/pipelines/mod.rs, src/shell/job.rs, src/shell/pipe_exec/fork.rs, src/shell/pipe_exec/mod.rs
Fixes #539, or at least partly.
Warning: Untested! Disowning doesn't seem to do anything, processes aren't closed either way.
=> Disown using &!

examples/array_methods.ion, examples/array_methods.out, manual/src/ch05-05-method.md, src/parser/shell_expand/words/methods/arrays.rs
- Add the missing @reverse() array method as documented in #441
- Added documentation for it
**State**:  ready
**Related**: #441
=> Add @reverse() method (#441)

src/lib/sys/redox.rs
**Problem**: execve and fork_and_exec share a large chunk of code
**Solution**: Remove the argument building and path resolution in fork_and_exec and call execve instead
- There is no more repeated code between fork_and_exec and execve
**Drawbacks**: Ion forks even if the file doesn't exist, whereas before it wouldn't.
**State**: Ready
=> Call execve from fork_and_exec in sys/redox.rs so they can share code

README.md
=> Fix issue board link

src/lib/builtins/mod.rs
=> Clean up builtin isatty

src/lib/lib.rs, src/lib/shell/binary/mod.rs, src/lib/shell/mod.rs, src/lib/shell/pipe_exec/job_control.rs, src/main.rs
That's one less TODO.
I'm planning on sending another PR after this one to use [clap-rs](https://clap.rs/) over a custom parser.
Please give me your opinions on that.
=> Move binary::main into actual main

README.md
Makes README clearer by moving introduction to top.
=> Make README clearer

src/lib/shell/directory_stack.rs
Closes https://github.com/redox-os/ion/issues/684
=> Fix cd'ing into a symlinked directory losing the original path

README.md
Just being a good boy scout. :)
=> Small grammatical fixes to readme

.travis.yml
This should fix builds so that PRs can be merged.
=> disable Redox travis builds until Redox builds are fixed

src/lib/shell/directory_stack.rs
`pushd` was not resolving special symbols in the path which `confuses set_current_dir`.
Make sure `pushd` uses same logic as `cd` to normalize paths.
=> fixes #696 pushd problem

.github/ISSUE_TEMPLATE
So users don't have to delete them themselves or have a cleaner issue if they don't
=> Comment out details in the github issue template

src/lib/parser/shell_expand/ranges.rs
**Problem**: I wanted `{03..07}` to expand to `03 04 05 06`, as on bash or zsh.
**Solution**: I added a new argument `nb_digits` to range-generating functions, so the output number is padded to get the expected number of digits. Note that `-` counts as a digits in order to get proper alignment when dealing with both negative and positive numbers (like bash and zsh do).
- The behavior of ranges like `{03..07}` changes.
**Drawbacks**: slightly slower, because we have to do some lookup (of at most two characters) and `format!` uses a loop to pad
**TODOs**: nothing
**Fixes**: my personal workflow when I want to match files numbered with leading zeroes to sort alphabetically
**Blocking/related**: none
**Other**: none
=> Add support for padded range expansion.

src/lib/shell/completer.rs
Removes an unneeded Vec allocation for the splitting
=> First step to refactoring completer.rs

src/lib/shell/completer.rs
Removes a couple `Vec` and `String` allocations but needs a ~~couple of~~ Box ~~traits~~ trait
=> Refactor filename completion as an iterator

src/lib/shell/pipe_exec/mod.rs, src/lib/sys/redox/mod.rs, src/lib/sys/unix/mod.rs
Fixes issue introduced by aa504277576e693adb4b566c7647bd9813480c1f
=> Fix compilation on redox

src/lib/shell/pipe_exec/foreground.rs, src/lib/shell/pipe_exec/job_control.rs, src/lib/sys/redox/job_control.rs, src/lib/sys/unix/job_control.rs
Fix a bug, + slight macro refactor.
Closes #706 
@stratact Would like to have your review of this PR to see if it also works on your system.
=> Fix for #706

src/main.rs
This fixes #682 but it hangs when doing redirection inside an Ion session, ~~probably likely due to the looping mentioned in https://github.com/redox-os/liner/pull/2~~
~~This PR also requires Ion to migrate to our Liner fork with https://github.com/redox-os/liner/pull/2 merged.~~
=> Fix for #682

examples/braces.ion, examples/braces.out, src/lib/parser/shell_expand/mod.rs
=> Fix for #768
