redox-os/ion

.travis.yml
Cargo.toml
src/input_editor.rs
src/main.rs
src/tokenizer.rs

The only functional difference in this change should be that the shell now supports basic quoting. There was a lot of refactoring along the way. Look through the commit log for more details on what I did. Each commit should have an informative message with more details beyond the first line.

Add basic support for escaping into ion

---

src/main.rs

These commands did nothing and could never be accessed because of how
on_command is written. The only reason I could think to include them
would be to have them show up in help. However, they did not have any
help strings and I don't think the grammar for the language should be a
built into the command that lists the available builtins.

Remove empty commands `if`, `fi`, and `else`

---

src/main.rs

Handle Result types and a few minor changes. Only one compiler warning
should be left, which is the use of std::thread::sleep_ms. I am leaving
this for now so that I don't have to go into redox and make sure the
Duration API exists in our clone of std.

Cleanup most compiler warnings with error messages

---

src/builtin.rs
src/expansion.rs
src/main.rs
src/parser.rs
src/tokenizer.rs

* Remove an unneeded clone
* Cleanup the way `#[derive]` is used on a few types
* Derive `Default` for `parser::Job` and use `Job::default()` instead of `Job::new()` which did the same thing
* Use BTreeMap for shell variables to have it automatically be sorted for reading
* Remove an unneeded binding in `on_command()`
* Use a type alias for `BTreeMap<String, String>` everywhere for easier maintenance

Lots of cleanup and refactor

---

src/builtin.rs
src/expansion.rs
src/main.rs

The problem with the way `main.rs` was written, was that it ignored a fundamental rule to encapsulation completely and when you do that, you end doing more work for the object rather than having the object do the work for you. Having the object do the work, allows the programmer to be code correct without having to think about it and not needing to mess with the object's data. So, I moved all of the rogue functions into `Shell` methods which is where they seem to belong, made all `Shell` fields private, cleaned up the signatures, and let the `Shell` object speak for itself.
As a result the code ends up looking cleaner this way and makes it easier for the programmer, API-wise.

Move rogue functions to methods and cleanup

---

src/flow_control.rs
src/main.rs
src/peg.rs
src/variables.rs

You can do some fun stuff with this for loop like
```
for i in 1 2 3
echo $i
end
```
However, this implementation is a little messy and does not play nice with other flow control commands. That means no nesting `if` or `for` inside a for loop. Obviously that will have to be fixed. I am merging now because I doubt I will be able to take it to the next level tonight.

Add partially working for loop

---

src/directory_stack.rs
src/flow_control.rs
src/history.rs
src/main.rs
src/status.rs
src/variables.rs

There are a couple other return status related changes in this patch.
Barring the TODOs added to the code, exit statuses should behave about
how you would expect now.

Make builtin commands return exit statuses

---

src/variables.rs

The `let` command now works like this:
- `let x=foo` creates a variable called `x` with a value of `foo`
- `let x` deletes the variable `x`
- `let` lists all the variables with their value

Fix the let command

---

src/main.rs

Instead of the current verbose error message when an invalid command is entered, what if we were to print a traditional error message like so:
ion:/home/mmstick/Programming/Rust/ion# HELP
ion: command not found: HELP

Less Obnoxious Error

---

src/main.rs

Following prior suggestions, this has been rewritten to use if let instead of a match.

Use 'if let' Instead

---

src/history.rs
src/main.rs

This will allow Ion to exit with the last command's exit status. The previous command's exit status is stored inside the `History` structure attached to the `Shell`.

Exit With Previous Status

---

src/directory_stack.rs
src/history.rs
src/main.rs
src/variables.rs

Several changes were necessary to allow Ion to use variables for tuning the shell. The `History` structure, for example, no longer needs to have a `max_size` variable because this information is already stored as a variable in the shell. This patch adds a few system variables such as `CWD`, `HISTORY_FILE`, `HISTORY_FILE_ENABLED`, `HISTORY_SIZE`, and `DIRECTORY_STACK_SIZE`. It also adds the capability for history being logged to a history file, named `ion_history`. What's currently lacking from this implementation is limiting the size of the history log and not logging commands loaded from files in history.

Ion Variables Patch

---

Cargo.toml
SYNTAX.md
src/flow_control.rs
src/function.rs
src/main.rs
src/peg.rs
src/pipe.rs
src/variables.rs

This required some minor changes to the grammar which propagated through the rest of the code base. When using a pipeline builtin functions are ignored at this time. The logic for executing commands was updated into an undesirable state because of the complications with builtins. Piping logic was added  in a new file.

Add piping from one process to another

---

src/history.rs
src/variables.rs

You can now expand strings containing multiple variables (see the `expand_several_variables` test). The parser is incomplete for now (no escaping) and quite simplistic.

More flexible variable expansion

---

src/history.rs

This will allow the history file to be truncated by a specified maximum number of commands, removing the topmost elements from the file so that a new command may be added at the bottom in their place.

Enable Truncation of History File

---

SYNTAX.md
src/flow_control.rs
src/function.rs
src/main.rs
src/variables.rs

Syntax:
This creates a function called `print_two_strings` which takes two arguments:
```
fn print_two_strings first second
echo $first $second
end
```
And this will call the function:
```
ion:# print_two_strings "Foo" "Bar"
Foo Bar
```

Add functions with arguments

---

src/main.rs
src/variables.rs

The decision is not taken yet AFAIK, so if you agree on using `unlet` to delete variables then you can merge this, otherwise just close this PR. In my opinion the current syntax is not clear, I think `unlet` is better.
Fixes #159

Add the unlet command

---

src/flow_control.rs
src/history.rs
src/main.rs
src/pipe.rs
src/variables.rs

**Problem**: Non-Idiomatic Rust
**Solution**: Fixes applied by Clippy
- Implement **Default** traits
- Do not use **.iter()** for basic looping
- Do not use **if not** conditionals
- When matching a single character, match as a character instead of a string
- Remove unnecessary **return** keywords
- Move the bulk of **main()** into **shell::execute()**

Clippy Fixes

---

src/main.rs
src/variables.rs

- Make `PWD`, `OLDPWD` and `HOME` environment variables
- Add the `export` command which sets environment variables.
Usage: `export KEY=VALUE`

Add the export command

---

Cargo.toml
src/main.rs
src/variables.rs

**Problem**: `tilde_expansion` uses the `regex` crate, which Redox doesn't support. See #168 
**Solution**: Rewrite `tilde_expansion` to remove `regex` dependency.
**Fixes**: #168

rewrite tilde_expansion to remove regex dependency

---

src/directory_stack.rs
src/history.rs
src/main.rs
src/variables.rs

**Problem**: Tilde expansion does not support accessing the directory stack.
- tilde expansion supports the directory stack
- `Variables.expand_*()` methods now have a `directory_stack` parameter
- new `Variables.get_var_or_empty()` method designed to replace many uses of `Variables.expand_string()`, to increase performance and prevent needing to pass the dir stack around as much
**Drawbacks**: New parameter in the `Variables.expand_*()` methods
**Fixes**: #156
**State**: Ready

add directory stack support to tilde expansion

---

src/directory_stack.rs
src/history.rs
src/input_editor.rs
src/main.rs
src/variables.rs

This change will merely modify error handling in a handful of situations to the methods provided by the `Option` and `Result` types for more functional-style error handling, which uses much less lines of code to achieve the same effect. It will also fix a few clippy warnings and makes changes to a few areas where files were being read directly into a `String::new()` without calculating the capacity beforehand, and values were being unnecessarily cloned.

Rustify Error Handling

---

src/directory_stack.rs

`switch_to_home_directory()` was called every time, making paths relative
to the home directory instead of the current directory.

Fix cd command

---

src/main.rs
src/variables.rs

This change adds support for brace expansions to support permutating elements. This also adds support for expanding variables within braces.
```sh
$ echo The pro{digal,grammer,cessed,totype,cedures,ficiently,ving,spective,jections}
The prodigal programmer processed prototype procedures proficiently proving prospective projections
```
```sh
$ echo The {barb,veget}arian eat{ers,ing} appl{esauce,ied} am{ple,ounts} of eff{ort,ectively}
The barbarian vegetarian eaters eating applesauce applied ample amounts of effort effectively
```
```sh
$ echo ion:${PWD}#
ion:/home/redox#

Add Brace Expansions

---

src/variables.rs

This will fix the issue of variables not being expanded if there's more than one variable expansion within a word. It will also allow using colons to separate variable expansions, without requiring braces. Tests have also added to ensure that the functionality works.
```sh
$ let FOO = foo
$ let BAR = bar
$ echo $FOO:$BAR
foo:bar
$ echo ${FOO}:${BAR}
foo:bar
```

Improve variable brace expansion

---

src/completer.rs
src/main.rs
src/variables.rs

This implements #183 by adding a `MultiCompleter` struct which combines several completers into one, and by adding a `BasicCompleter` with the function names and command names combined.

Tab completion for functions and built-in commands

---

src/main.rs
src/shell_expand/braces.rs
src/shell_expand/mod.rs
src/shell_expand/words.rs
src/variables.rs

Provides a handful of changes to improve the `job_expand()` method in **variables.rs**, and some improvements to the **shell_expand** module in regards to error handling. Errors are now captured in the `words.rs` module instead of in the `braces.rs` module, which was causing a bug with improperly detecting some unmatched braces. Error messages will now also fully print the original command and correctly point out the location of the unmatched brace. An additional unit test was also added for the shell expand module.

Improve Job Expansion & Better Error Handling

---

Cargo.lock
Cargo.toml
src/grammar.rustpeg

peg 0.3 was no longer building on nightly, and updates are now to 0.4 with breaking changes. This upgrades to 0.4 and unbreaks those changes in the grammar.

Upgrade peg to 0.4

---

Cargo.toml
src/grammar.rustpeg
src/peg.rs
src/shell_expand/mod.rs
src/shell_expand/words.rs
src/variables.rs

This change will address all the major issues with the grammar in regards to handling spaces, quoting, and shell expansion strings.
```bash
echo $(ls | grep Cargo)
> Cargo.lock
> Cargo.toml
let A="one  two  three"; echo $A
> one  two  three
echo ABC"123 456"DEF"789 '101112'"
> ABC123 456DEF789 '10112'
```

[Ready to Merge] Grammar Fixes

---

src/grammar.rustpeg
src/peg.rs

Embarrassingly, a tiny bug in the last pull request caused redirection to not work. Process expansion also wasn't working when that process contained a semicolon. This change will fix that. It's now possible to use commands like the following:
```sh
echo $(ls > temp; cat temp | grep Cargo)
```

[Ready to Merge] Redirection & Process Expansion Fixes

---

src/grammar.rustpeg
src/peg.rs

This change will convert the existing pipeline collector in the grammar into an `Iterator` to eliminate heap allocations caused by pushing to a `Vec`.

Convert Vec to Pipeline Iterator

---

src/shell_expand/mod.rs
src/shell_expand/words.rs
src/variables.rs

This will fix the issue of newlines not being retained when a variable is quoted.
Example:
```
let A = "$(seq 1 10)"; echo $A; echo "$A"
1 2 3 4 5 6 7 8 9 10
1
2
3
4
5
6
7
8
9
10
```

Quoted Variables Retain Newlines

---

src/shell_expand/braces.rs
src/shell_expand/variables.rs
src/shell_expand/words.rs

The shell expansion logic contains a large number of boolean values, each which will consume 8 bits of memory and an 8-bit register even though booleans are logically 1-bit values. By collapsing all the booleans into a single 8-bit integer and using bit-twiddling operations, shell expansion should be much faster and use less memory.
This also allows me to refactor some code in shell expansion to keep Clippy quiet.

Bit Twiddling in Shell Expansion

---

src/main.rs

this fixes the build on the latest rust nightly build 2017-01-31. It's apparently no longer needed. Not really sure why it counts as a full-on build stopping error, though.

Remove unncessary attribute #![feature(deque_extras)]

---

src/main.rs

Added expansion of variables when evaluating if statements.
Undefined variables will evaluate to empty strings, thus the equality of two undefined variables will evaluate to True.
This is the same behaviour of other shells such as Bash, Sh, Zsh, ...

Expand variables in if statements (fixes #212)

---

src/flow_control.rs
src/grammar.rustpeg
src/main.rs
src/peg.rs
src/shell_expand/mod.rs
src/variables.rs

This change will connect the for grammar to shell_expand, thus enabling
the possibility to write expressions like so:
```fish
for index in $(seq 0 10)
echo $index
end
```
This also implements inclusive and exclusive ranges. Not sure if we want to go with this syntax, but I figured I'd use the same syntax as Rust.
```fish
for index in 0...10
echo $index
end
```
```fish
for index in 0..11
echo $index
end
```
Eliminates the need to use the `seq` command.

For Grammar Improvements

---

src/grammar.rustpeg
src/main.rs

This makes it possible to now write commands like so:
```fish
for index in $(seq 1 10); echo $index; end
```

Split Statements

---

src/parser/shell_expand/words.rs
src/parser/statements.rs

With this change, the parsing bugs have been resolved, and it's now possible to write commands like the following:
```sh
let current_branch = $(git status -b | awk 'NR == 1 {print $3}')
let modified = $(git status | rg 'modified' -c)
echo $(echo one $(echo two) three)
```

Parser Fixes

---

src/parser/shell_expand/variables.rs

Adds the ability to pass variables into subshells by expanding inner variables before performing process expansion. Therefore, the following command is now valid:
```sh
let A = "abc"; echo $(echo ${A} $A$A $(echo $A))
```

Expand Variables In Process Expansions

---

src/flow_control.rs
src/parser/peg.rs
src/parser/pipelines.rs
src/pipe.rs
src/variables.rs

Resolves issue #227 by implementing support for `&&` (**AND**) and `||` (**OR**) operators. There's also basic background support, so background jobs will run in the background and print when they are complete.
The following command:
```sh
echo one && echo two && echo three
```
Will print
```
one
two
three
```
While the following:
```sh
echo one && echo two || echo one
```
Will print
```
one
two
```
And the following:
```sh
ecsdf one && echo two && echo three || echo four
```
Will print
```
ion: command not found: ecsdf
four
```

Implement `&&` and `||` Operators

---

src/completer.rs
src/main.rs

Sorry for my awful english
**Problem**: I add some code for add completions from all ${PATH} directories;
- I rewrite ```MultiCompleter``` to use ```Vec<FileCompleter>``` instead of ```FileCompleter```

Fix : src/main.rs : 103 file_completers for all directories in ${PATH}

---

src/builtins/README.md
src/builtins/mod.rs
src/builtins/variables.rs
src/main.rs
src/parser/loops/for_grammar.rs
src/parser/loops/while_grammar.rs
src/parser/mod.rs
src/pipe.rs
src/variables.rs

- The let/alias/export/drop commands have been refactored into a builtins module
- A README.md file was created for documenting the builtins module and the commands contained within.

Refactor Let/Alias/Export & Implement Builtin README

---

src/builtins/README.md
src/builtins/variables.rs

WIth this change, it is possible to take variables which contain numbers, and apply basic arithmetic to them using the let command, without the need for an external application. It performs 32-bit floating point math, so irrational numbers are supported.
```ion
let a = 1
echo $a
let a += 4
echo $a
let a *= 10
echo $a
let a /= 2
echo $a
let a -= 5
echo $a
```
```ion
let a = 1;
while test $a -lt 100
echo $a
let a += 1
end
```

Implement Basic Arithmetic for Let/Export

---

Cargo.toml
src/main.rs
src/variables.rs

This commit adds support only for non-Redox unix systems. Others just fall back to stubs.
Recreation of #186.
Issue #155

Implement tilde expansion for other user's home directories.

---

src/builtins/functions.rs
src/builtins/mod.rs
src/shell/mod.rs

When fn is typed with no arguments, print a list of functions that are
currently defined. For [Issue 242](https://github.com/redox-os/ion/issues/242)
Example output:
- [...]
- [...]
- [...]
**Drawbacks**: [if any, describe the drawbacks of this pull request.]
ready
**Blocking/related**: [issues or PRs blocking or being related to this issue.]
**Other**: [optional: for other relevant information that should be known or cannot be described in the other fields.]
------
_The above template is …

Print currently defined functions - Issue #242

---

src/builtins/functions.rs
src/flow_control.rs
src/parser/grammar.rustpeg
src/parser/peg.rs
src/shell/flow.rs

**Problem**: Adding description to functions.
**Solution**: I have modified the rustpeg file in order to parse the added description. I have added the description field to the Function struct and to the struct that represents a function in the Statement enum. Now a function can be declared this way: ```fn name_of_func arg1 arg2 ... argN -- description```. The  description is optional in the parser. I have changed the print_functions function in function.rs such that when a description exists it will print it alongside the name of the function. 
**Changes introduced by this pull request**: I had to add the description field in flow.rs in different points. I've added tests for parser.
**Fixes**: #232

added description for functions

---

Cargo.toml
src/ascii_helpers.rs
src/builtins/calc.rs
src/builtins/echo.rs
src/builtins/functions.rs
src/builtins/mod.rs
src/builtins/set.rs
src/builtins/source.rs
src/builtins/test.rs
src/builtins/time.rs
src/builtins/variables.rs
src/main.rs
src/parser/assignments.rs
src/parser/grammar.rustpeg
src/parser/loops/for_grammar.rs
src/parser/mod.rs
src/parser/peg.rs
src/parser/pipelines.rs
src/parser/shell_expand/mod.rs
src/parser/shell_expand/words.rs
src/shell/assignments.rs
src/shell/flow.rs
src/shell/flow_control.rs
src/shell/history.rs
src/shell/job.rs
src/shell/mod.rs
src/shell/variables.rs
src/smallstring/Cargo.toml
src/smallstring/src/lib.rs
src/types.rs

We allocate a lot
Use `SmallVec` and `SmallString` (based on `SmallVec`) to allow small vectors and strings to be stored on the stack.
Some public API functions that took `String`s take `SmallString`s now. Also, it's now even faster on my machine.
- [...]
- [...]
- [...]
**Drawbacks**: [if any, describe the drawbacks of this pull request.]
Clean up the code, unify the methods of creating a singleton smallvec (probably with a macro), move the typedefs to a `types` module.
WIP …

Increase amount of work done without allocation

---

Cargo.toml

Ion still takes literally any time to run
Add LTO and panic=abort. Unfortunately, this still causes Ion to take some time to run, but it's 15% closer to the eventual goal of completing instantly.
- [...]
- [...]
- [...]
**Drawbacks**: [if any, describe the drawbacks of this pull request.]
**Blocking/related**: [issues or PRs blocking or being related to this issue.]
**Other**: [optional: for other relevant information that should be known or cannot be described in the other fields.]
LTO …

Add LTO and panic=abort for ~15% speedup

---

examples/run_examples.sh

This commit is for the discussion of issue [#952](https://github.com/redox-os/redox/issues/952) of `redox` repository.
This change is very similar to https://github.com/redox-os/libc-artifacts/pull/7.

change shebang of run_examples.sh to make the script to be ran on both Linux or BSD

---

src/parser/shell_expand/words.rs

**Problem**: Statements such as `foo\(\)` were not being correctly parsed, see #291.
**Solution**: Whenever a character is read by a `WordIterator` when the `BACKSL` flag is set, the flag gets unset.
- Backslash flag now reset upon reading the escaped character
- Add regression test for multiple backslashes
**Drawbacks**:
- It could use some more tests for these sorts of use cases
- It is unclear if this affects the other uses of the `WordIterator` beyond parsing command line statements.
**Fixes**: Resolves #291.
**State**: Ready with the caveat of adding more unit / regression tests, also formatting and such.

Correctly parse statements with multiple escaped characters

---

examples/glob.ion
examples/glob.out
src/parser/shell_expand/mod.rs
src/parser/shell_expand/words.rs
src/shell/flow.rs
src/shell/job.rs

**Problem**:Globbing during shell expansion (see https://github.com/redox-os/ion/issues/258)
**Solution**: I added an extra param to the Normal token which designates it as a normal token that's globable or not.
- Globbing gets moved and probably (isn't) yet parsed 100% correctly. I'm just submitting this PR so I can get in touch with contributors and notify other people of my attempt at trying to fix this.
**Drawbacks**:
Wildcards during quotes don't parse correctly.
Make sure wildcards in quotes get parsed as text (if this happened during the previous version).
https://github.com/redox-os/ion/issues/258
Ready for …

Moving the glob parser

---

src/builtins/variables.rs
src/parser/loops/for_grammar.rs
src/parser/mod.rs
src/parser/peg.rs
src/parser/shell_expand/mod.rs
src/parser/shell_expand/ranges.rs
src/parser/shell_expand/words.rs
src/shell/assignments.rs
src/shell/mod.rs
src/shell/variables.rs

**Problem**: There is no way to refer to, for example, the second to last element of an array aside from `@array[len(array) - 2]` where `len` gets the number of elements in an array.
**Solution**: Extend Ion's syntax to allow for this through negative indices, such as in Python:
```
$ let array = [ 1 2 3 4 5 6 ]
$ echo @array[-1]
6
$ echo @array[1..-2]
2 3 4
```
- Introduce new data structures that represent indexing from the end of an array
- Update parsing of array ranges and indices to use these new structures
**Drawbacks**:
- `parser::shell_expand::words` has become a bit of a mess with a bunch of `Index` named classes everywhere. As discussed in #263 it would be useful to refactor this and move some of the logic repeated at call-sites, but …

Add semantics for indexing into arrays with negative indices 

---

src/builtins/calc.rs

**Problem**: ² and ³ are obvious mathematical characters (my terminal even changes ^2 into ²), but triggered errors in calc.
**Solution**: Added two specific tokens, square and cube, to the calc tokens. 
- Added these tokens and added some code in the exponentiation fn.
**Drawbacks**: I think none.
**TODOs**: Maybe write a test?
**Fixes**: None. I was playing around in calc and noticed this.
**State**: Ready.
**Blocking/related**: I think none.
**Other**: None
------

Parse ² and ³ as one would expect in the calc command

---

src/builtins/variables.rs
src/parser/loops/for_grammar.rs
src/parser/mod.rs
src/parser/peg.rs
src/parser/shell_expand/mod.rs
src/parser/shell_expand/ranges.rs
src/parser/shell_expand/words.rs
src/shell/assignments.rs
src/shell/mod.rs
src/shell/variables.rs

**Problem**: The extra features introduced in #297 made it clear that `Index` `IndexStart` and `IndexEnd` were confusing to exist all together. 
**Solution**: This PR consolidates and appropriately separates the responisbilities of `Index`, `IndexStart`, and `IndexEnd` into `Select`, `Range`, and `Index.
- Replaced top-level `Index` with `Select` which better captures the meaning of the enumeration: a selection of an array versus an index, which brings to mind a single element within the array.
- Added a separate `Range` struct that encapsulates inclusive vs. exclusive
- Consolidated `Index<blah>` into `Index::Forward` and `Index::Backward` and removed all of the `CatchAll` values. `CatchAll` is now represented by `Forward(0)` or `Backward(0)`. …

Refactor `Index`, etc. into `Select`, `Range`, and `Index`

---

README.md

**Problem**: vi and emacs keybindings are now supported, but missing from the feature list.
**Solution**: I added the fact that `set -o (vi|emacs)` is now supported by ion.
**State**: Ready
**Blocking/related**: Issue #289 fixed by commit [ce0a196](https://github.com/redox-os/ion/commit/ce0a19672e7d76c4ff431bffa2731852a893157e)

Updat README.md to add vi/emacs keybindings as a feature and fix a typo in example code

---

src/builtins/mod.rs
src/builtins/variables.rs
src/parser/grammar.rustpeg
src/shell/assignments.rs
src/shell/flow.rs
src/shell/flow_control.rs

**Problem**: `export` not being in the grammar meant that the RHS was eagerly expanded.
**Solution**: `export` now has the same semantics as `let` but instead of storing the variable locally, it is written to the OS environment.
- `export` is now in the PEG grammar and has an associated `Statement` enumeration
- `export` and `let` now have the same logic except, as mentioned, `export` writes to the OS environment
- DRYed up the logic, including replacing a custom made `ExpanderFunctions with `get_expanders!`
**Drawbacks**: Nothing off the top of my head 
**Fixes**: Related to #255
**State**: Ready!

Move `export` into the grammar

---

src/parser/statements.rs

At some point in the history of `StatementSplitter` it started rejecting braced variables such as `${foo}`. While working on #262 I noticed this.
The problem was that the first case, which catches any character that cannot be in a braced variable, also threw an error for a brace, even though that might be the valid end of a braced variable.

Fix braced variables not parsing correctly

---

Cargo.lock
Cargo.toml
src/builtins/echo.rs
src/main.rs
src/parser/pipelines.rs
src/parser/quotes.rs
src/parser/shell_expand/words.rs
src/parser/statements.rs

**Problem**: There are small ergonomics issues with using hand-rolled bit flags as described in #308.
**Solution**: Replace the use of the hand-rolled flags with auto-generated `bitflags` structures that provide nice mnemonics for membership while being mostly compatible with the old syntax.
- Bitflags have been replaced with `bitflag!` equivalents as per the [bitflag crate](https://docs.rs/bitflags/0.9.1/bitflags/)
- I'm not entirely sure if this is any more readable than before: part of the problem is `contains` versus `intersects`, where `foo.contains(bar)` is `foo & bar == bar` and `foo.intersects(bar)` is `foo & bar != 0`. These names are non-intuitive.
- In addition to the above, the operators tended to be much more …

Replace manual bit flags with auto-generated bit flag construct

---

Cargo.toml
src/main.rs

Closes #314.
I'm still trying to set up a redox environment (see: https://github.com/redox-os/redox/issues/970; I'm giving up trying to do this locally for now, spinning up Ubuntu VM) but in the meantime this should work.

Hide Tokio crates behind cfg gate for Redox

---

src/builtins/calc.rs
src/builtins/mod.rs
src/parser/shell_expand/mod.rs
src/parser/shell_expand/words.rs
src/parser/statements.rs

**Fixes**: Closes #243 
- Builtin `calc` functionality is now exposed to the rest of the crate
- Added support for the `$((...))` syntax form which is equivalent to `calc '...'` with some syntactic sugar for referring to variables
- The `calc` builtin is now tightly coupled to the rest of the crate: I don't feel this is desirable
**TODOs**: 
**State**: Core functionality should be there, needs some polish

[WIP] Add arithmetic sub-expressions to Ion's syntax

---

src/parser/shell_expand/words.rs

**Fixes**: Closes #324. 
The glob match case incremented `self.read` in addition to the increment that occurs after the match statement. This caused `self.read` to be larger than the length of the input string.

Remove extra read increment in glob branch

---

src/parser/shell_expand/words.rs

**Problem**: Users cannot iterate over the contents of a string easily.
**Solution**: Add in three new `ArrayMethod`s that map from string variables to arrays:
- `@graphemes(..)` iterates over the unicode graphemes of the string as per [this crate](https://github.com/unicode-rs/unicode-segmentation)
- `@bytes(..)` iterates over the UTF-8 byte sequence that corresponds to the given string
- `@chars(..)` iterates over the unicode scalars of the byte sequence as per [`String::chars`](https://doc.rust-lang.org/std/string/struct.String.html#method.chars)
- Add the three above methods to `parser::shell_expand::words`
- Introduce a new trait for applying a `Select` variant to an iterator DRYer
- The `SelectWithSize` trait is not …

Add `@graphemes(..)`, `@bytes(..)` and `@chars(..)`

---

src/parser/shell_expand/mod.rs

- Refactored `array_expand` to be the entry point for any `Select`ion into an array of words, DRYing up the code along the way
- Squashed a subtle bug where reverse indexing into an array that expanded to a larger array (for example the array `@[[foo bar] [baz quux]]` would incorrectly use the original length of the array and not the expanded length. This has been resolved by getting a reversed iterator over the array instead of using the size to resolve the true length.
- Added a regression test for the above
**Other**: The majority of my time spent on this PR was trying to figure out the best way to expand `Select` code reuse:
- I'm probably overthinking this. Just having functions like `array_expand` work beautifully; …

Refactor `array_expand` (and squash bug)

---

src/shell/mod.rs

**Related Issues**: Closes #321 
**Changes introduced in this pull request**:
- `Shell::readln` now determines if the first word is either an existing directory, or is potentially a directory (i.e. if the parent exists as a folder)
**TODO**:

Shell::readln now completes to a filename if the last word is a file 

---

src/parser/shell_expand/words.rs

- Allow the empty string to be parsed as `WordToken::Normal("")` by allowing a double quote to be the first char of a `WordToken::Normal` sequence
- Added a case where if a `WordToken::Normal` would be the empty string, replace it with whatever the next token would be
- This prevents cases like `"$FOO"` from generating empty tokens due to having a quote immediately before a `$`
- Added a regression test for this behavior
**Fixes**: Closes #345.

Empty string can now be passed in as an argument to a function / command / etc.

---

src/shell/mod.rs

The problem was that for any filename "foo", `readln` would check to see if either it exists, or if the parent exists. Which means if you're trying to complete _any_ executable, it thinks its a file because the "parent" is the current directory.
Closes #352.

Fixed completing executables

---

src/shell/mod.rs

Due to the condition that the parent directory cannot be the current directory, simple commands like `rm file_in_this_dir.txt` were broken.

Additional fix for #352

---

examples/run_examples.sh

In particular, `glob.ion` was failing if I ran `run_examples.sh` in the examples folder.

Force run_examples.sh to use project root as working directory

---

build.rs

Updated the MIN_VERSION of rustc to be 1.19.0 and the comment to
reference the RFC/GitHub issue that is the reason behind the version
requirement.
I also updated the error printed if the minimum version is not met to
reflect this version.

Update minimum rustc version requirement

---

README.md
src/builtins/job_control.rs
src/main.rs
src/shell/flow.rs
src/shell/job_control.rs
src/shell/pipe.rs

This PR removes hardcoded signal numbers and adds `-1` to the PID when sending SIGCONT. #29
Tested on FreeBSD, Arch Linux and the Windows Subsystem for Linux. Redox might be even more broken though.

Job control: libc constants, pid fix

---

Cargo.lock
Cargo.toml
src/main.rs
src/shell/mod.rs
src/shell/variables.rs

Read init file from the XDG App Dir using the app_dirs crate.
The init file is now named initrc instead of .ionrc.
---
Fix Issue #326 
I wasn't sure how to format some of these changes (like the author name or the struct declaration inside a function call), please feel free to modify it.
Moreover, it looks like some others things could be moved into the app dir (history file)?

Store configurations in the correct XDG App Dir

---

src/main.rs
src/shell/flow.rs
src/shell/job_control.rs
src/shell/pipe.rs

Redox build was breaking for a number of reasons:
- Apparently the crate for Redox syscalls is just `syscall`, which is news to me
- `libc` is only imported for Unix and non-redox, which means any case where we refer to a `libc` constant needs to be behind a `cfg`
- The Redox version of `watch_pid` had a different number of arguments

Fix redox build

---

src/shell/completer.rs
src/shell/mod.rs

**Fixes**: Closes #348.
- Add `unescape` which maps from escaped strings to their raw counterparts
- Add custom logic for determining word boundaries for `liner` completions; this is based off the default completer with some adjustments for backslash.
- I can't remember who, but someone mentioned that we ought to have some central list of what should get escaped / un-escaped; this builds on the problem without fixing it. Additionally this does not allow something like:
```
$ touch "foo(bar)"
$ rm "foo(<Tab>
```
to autocomplete `"foo(` to `"foo(bar)"`.
**State**: Ready to go!

Fix autocomplete for partially escaped filenames

---

src/shell/mod.rs

**Fixes**: Closes #356.
- Prints a warning if the user executes a script and there is still a statement in memory (i.e. `flow_control.level != 0`

Add warning when a script completes with a statement in memory

---

Cargo.toml

**Problem**: There's a bug in version_check < 0.1.3 that lets the check fail on Arch Linux (and possibly other rustc builds)
**Fixes**: #393

Update version_check to 0.1.3

---

src/builtins/test.rs
src/shell/mod.rs

- `tests.rs` now avoids the use of `unwrap` and is more generic on the output buffer.
- When Ion is invoked as `-c`, forward the empty string appropriately if given as an arg in `args()`
**Fixes**: Closes #387

Test can now interpret the empty string + fresh coat of paint

---

src/parser/pipelines.rs
src/shell/completer.rs

- Quotes are now considered escaped characters as per `IonFileCompleter`
- `pipelines::Collector` now respects escaped characters in arguments, such as quotes
- `pipelines::Collector` also will now error if not at the top level of a job, i.e. not inside an array or subshell
**Fixes**: Closes #350

Resolve quotes not being an escaped character

---

src/shell/mod.rs

Introduced by commit ea4b98c94f21, an Option modifier on Context field in the
Shell struct.

Fix build by changing Option field

---

src/main.rs
src/parser/pipelines.rs
src/parser/shell_expand/mod.rs
src/parser/shell_expand/words.rs
src/types.rs

**Problem**: Writing `Array::from_vec(vec![...])` is verbose and performs more computation than needed.
**Solution**: Add an `array!` macro that replaces any instance of `Array::from_vec(vec![...])` with `array![...]`. Additionally it calls `into` on its elements, so instead of having to write:
```
Array::from_vec(vec!["foo".into(), "bar".into()])
```
it will be sufficient to write
```
array!["foo", "bar"]
```
**Drawbacks**: This creates an extra level of indirection: it is unclear what type the `array!` macro refers to. However I don't think it is any more indirection from before, where the `Array` type is just a `SmallVec` alias.

Add `array!` macro for creating inline `Array`s

---

examples/herestring.ion
examples/herestring.out
src/parser/peg.rs
src/parser/pipelines.rs
src/shell/pipe.rs

- Modified `Pipeline::stdin`'s type to be a union of either a filename or a string input
- Added support in `pipelines::Collector` for recognizing herestrings
- Added required functionality in `Shell::execute_pipeline`
**TODOs**:
**Fixes**: Closes #133
**State**: WIP; see TODOs. 
**Other**: This PR ended up being slightly different than #200; instead of holding onto the string and writing to `stdin` once the command had been spawned, this takes a cue from the implementation of `&|`: write the herestring to a pipe, close the writer end, and pass the reader end to the first command in the pipeline.

[WIP] Add support for herestrings

---

README.md

typo in "Braces Can Create Arrays" example

---

src/builtins/echo.rs

`echo` was treating everything preceded by - as an options flag so something like `echo -1` wouldn't output anything.
This change would make it act more like the usual `echo`, which would even take something like `echo -n1` and output `-n1` while `echo -n -1` would recognize the `-n` flag and output `-1` without a newline.

bugfix: echo was treating anything preceded by - as an option flag

---

src/shell/job.rs
src/shell/pipe.rs

Before when determining how to create the command the code would look at a hand maintained list which had to be updated whenever a new builtin was added. It looked like that was fairly out of date and caused some odd behavior. For example `true` and `false` weren't in the list so `true && false` wouldn't be using the builtins, but just `true` or `false` alone would be. Since the shell has the builtins hash I figured we can just check if it is in there or not by checking the keys and then call the appropriate method to create the command.

Jobs no longer use a separate list of builtins to determine the command type

---

examples/conditionals.ion
examples/conditionals.out
src/shell/pipe.rs

If you ran `false && echo and || echo or` you should have gotten "or" echoed, but instead nothing was coming out. It was caused by advancing these iterators. It looks like those lines were added [here](https://github.com/redox-os/ion/commit/9d5cb19d26d0744c9de48983d981b4d0da4984b7#diff-cc20bc374fba8d873a99948f7710250eL127), but I'm not exactly sure why. It references `&|`, but that seems to work fine without them.
Also added that examples script to help make sure they're still working in the future.

Conditionals && and || weren't working as expected

---

examples/not.ion
examples/not.out
src/builtins/mod.rs

`not` will run the command after it and flip any nonerror status code. 0 -> -1 and -1 -> 0.

Added not builtin

---

src/main.rs
src/shell/binary.rs

Execute the initrc file only when using ion in interactive mode as it probably makes less sense in the other modes.
Moreover, it fixes modification of the context done in the initrc file which weren't taken into account as the context wasn't initialized at the time of the script execution (e.g.: `set -o vi` in the initrc didn't set the vi editing mode in interactive sessions).

Read init file only when using interactive shell

---

examples/comments.ion
examples/comments.out
src/parser/statements.rs

This should fix issue #419, but I'm not sure if it is exactly how we want to do it. With this change any `#` not at the start of the line (`self.read == 1`) or preceded by an ascii whitespace character (`b' ' | b'\t'`) will be considered part of the token it is inside.

Fix issue #419 `echo hello#world`

---

src/parser/shell_expand/mod.rs
src/parser/shell_expand/words.rs
src/parser/statements.rs

- If the "variable" for a string or method looks like an expression (starts with `@`, `$`, etc.), it is expanded as if it were an expression, otherwise it is treated as a variable
**Drawbacks**: I feel like this PR has exacerbated some issues with how methods are parsed, for example:
```
$ let foo = bar
$ echo @len( @bytes(foo))
0
$ echo $len( foo)
<no output>
```
I'd like to make a sweep over how methods are parsed and do things like consolidating the logic for all the string methods, making it easier to pass in arbitrary values to methods, making `StringMethod`s work exactly like `ArrayMethod`s or vice-versa, etc. Also fixing the above.
**Fixes**: Closes #389
**State**: Good to go aside from **Drawbacks**

Add support for inline expressions in methods

---

src/parser/shell_expand/mod.rs
src/parser/shell_expand/words.rs

- `WordToken::StringMethod` now has an internal `struct` which manages the logic for string methods
- Changed `slice_string` to `slice` and allowed any input that satisfies `AsRef<str>`
------
Aside: I'm wondering if `WordToken` could be benefited from being more token-like: more lightweight than they are now. For example, instead of having an `ArrayProcess` that stores a string that will be tokenized later, we can just have an `ArrayProcessBegin` and `ArrayProcessEnd` then tokenize the contents.

Miscellaneous method updates / QoL changes

---

examples/match.ion
src/shell/flow_control.rs

- Instead of using `end` to signal the end of a case, case blocks are implicitly ended by either another `case` statement or the end of the `match` block.
**Fixes**: Closes #414 
**Other**: The description of #414 was "make end optional" but I figure we can just remove it altogether; thoughts?

Case statements are now implicitly ended

---

src/builtins/mod.rs
src/shell/mod.rs

We don't need the `Box<Fn(...)>` anymore in the builtins. The only thing this new `Builtin` doesn't allow is closures that capture an environment.
I'm going to start working on changing builtins to accept stdin, stdout, and stderr as parameters now.

Some more consistency changes to builtins

---

src/shell/pipe.rs

**Problem**: I found that while trying to echo to the example scheme (:vec) I was getting
EBADF which caused "command not found: /bin/ion" to be printed.
**Solution**: Only print "Command not found: ...", if the error is actually that the command
is not found. Otherwise print a general error description from the system.

Handle unusual errors during process spawning

---

Cargo.lock
Cargo.toml
src/builtins/mod.rs
src/main.rs
src/parser/grammar.rustpeg

Adding matches made me run into an issue with the grammar. Trying to run `matches hello '\w+'` actually started a `match` statement followed by the expression `es hello '\w+'` which was due to having `whitespace?` instead of `whitespace+`. This issue was in a few places. You could declare variables like `letfoo = bar` for instance.

Added `matches` builtin and fixed grammar issue

---

src/parser/mod.rs
src/parser/shell_expand/mod.rs
src/parser/shell_expand/words.rs
src/shell/variables.rs

**Fixes**: Closes #410 
**Drawbacks**: If a user wants the specific behavior of capturing a process and stripping newlines, it is slightly more cumbersome to do so (as `tr "\n" " "` doesn't work as expected).

`expand_process` changed to not strip newlines for quoted instances

---

Cargo.lock
Cargo.toml
src/builtins/mod.rs
src/main.rs
src/shell/fork.rs
src/shell/job_control.rs
src/shell/pipe.rs
src/shell/signals.rs
src/sys/redox.rs
src/sys/unix.rs

This set of changes moves most platform support into two simple files, `sys/redox.rs` and `sys/unix.rs`.
It also adjusts signal handling to use `signal` for compatibility with both Redox and Linux.
For the reviewer, probably @mmstick, I would like to know if signal behavior on Linux is the same as before this modification.

Simplify cross platform functions

---

src/parser/shell_expand/words.rs

**Problem**: Missing string methods
**Solution**: Add some of them
- $basename: Print NAME without leading directories
- $extension: Print extension of NAME
- $filename: Print NAME without extension (if there is one)
- $parent: Print parent of NAME (if there is one)

Add basename, extension, filename, parent

---

src/main.rs
src/shell/flow.rs
src/shell/job_control.rs
src/shell/mod.rs
src/shell/signals.rs

This creates an atomic bitmask of pending signals, and removes the extra signal handling thread. When a signal arrives, an atomic operation flips a bit in the bitmask. The handling code unflips the bit when it checks for signals, in the main thread.

Simplify signal logic so that it is safe and single-threaded

---

src/parser/assignments.rs
src/parser/mod.rs
src/parser/shell_expand/mod.rs
src/parser/shell_expand/words.rs
src/shell/assignments.rs
src/shell/variables.rs
src/types.rs

**Problem**: No map-like data structures yet exist in ion.
**Solution**: Allow simple associative arrays with string keys
- Create hashmap context in shell::variables to store named hashmaps
- Create "Key" selector to represent string keys
- Instances of "Select" objects must now be cloned; remove Copy trait
(This was needed to support a select type based on string keys)
**Drawbacks**: Select objects no longer implement Copy
**TODOs**: Does not yet have an initializer syntax for associative arrays 
**Fixes**: Addresses #246 
**State**: Needs review

Implement simple form of associative arrays

---

src/shell/binary.rs
src/shell/job_control.rs
src/shell/signals.rs
src/shell/variables.rs
src/sys/redox.rs
src/sys/unix.rs

Resolves #463. A non-flat replica of the module structure may be wanted in the future if `sys` grows, but I think this works fine for now.

Move OS #[cfg] functions to sys

---

src/sys/unix.rs

Make compilable on Mac. I don't think it has a pipe2 system call.

Compile on Darwin

---

src/sys/redox.rs

Compile for redox

---

src/builtins/mod.rs
src/builtins/variables.rs

Fix #453 
The `alias` built-in took an array of arguments so whitespace wasn't included. 
Now the array is joined by whitespace, and given to `alias` as is. 
`parse_assignment` didn't actually parse `let` bindings so I changed the name and documentation to reflect that.

include whitespace in alias argument

---

examples/builtin_piping.ion
examples/builtin_piping.out
src/shell/fork.rs
src/shell/job.rs
src/shell/job_control.rs
src/shell/pipe.rs
src/sys/redox.rs
src/sys/unix.rs

**Problem**: Currently if we have a builtin to be run as part of a pipeline, we just take the job, reconstruct it, and run a sub-process such as `ion -c builtin arg1 arg2`. This is problematic as it forces `ion` to re-parse the given arguments which is inefficient and bug prone ( #454 ).
**Solution**: Manually manage running builtins as part of a pipeline by forking the current process and executing the builtin in the child process.
- Replaced the use of `Command` in `shell::pipe` with `RefinedJob`; an enumeration that is either an external command or a builtin
- Modified `shell::pipe::pipe` to fork and execute a builtin for the `RefinedJob::Builtin` instance; behavior for `RefinedJob::External` is roughly the same as before: build a `Command`, …

Allow builtins to be executed as part of pipelines

---

examples/braces.ion
examples/braces.out
src/parser/shell_expand/ranges.rs

Half of #457 
Syntax is now:
`{1..2...7}` -> 1 3 5 7
`{1..2..7}` -> 1 3 5
`{a..2...e}` -> a c e
`{a..2..e}` -> a c
and similarly for backwards and negatives.
Also added some tests to the examples dir.
(I'm not sure why those two earlier commits are in this.. I let my repo get messed up somehow)

Added stepped ranges

---

src/shell/pipe.rs
src/sys/redox.rs
src/sys/unix.rs

- `shell::pipe::execute` will run a builtin in place and set the appropriate return code instead of forking
**Fixes**: Closes #332.

Run builtins in place when not part of a pipeline of data

---

src/shell/job.rs
src/shell/pipe.rs

- `shell::pipe::builtin` will not close any file descriptors: this will be done by `RefinedJob::drop` or inside the child process if appropriate. This prevents a double close in the case of a builtin being run in the parent process.
**Fixes**: Closes #478 
----
@mmstick: I'm thinking about replacing all of the `RawFd`s with `File`s. It would mean that `RefinedJob` doesn't need to have a custom `Drop` implementation and it means we are less dependent on *nix specific things. Thoughts?

RawFDs now managed by forked process, not shell::pipe::builtin, when appropriate

---

src/shell/job.rs

- If a job argument expands to the empty string, return an array containing the empty string instead.
- Added a regression test w.r.t. job expansion
**Fixes**: Closes #345 (again).
------
I wonder if it would be helpful to make a distinction inside Ion's code-base between string and array values. I.e. `Array` becomes `Value`, and `Value` becomes an enum like:
```
enum Value {
String(SmallString<...>),
Array(SmallVec<...>),
}
```
Though we probably can't use `SmallVec`; it would have to be `Vec` (I think).

Fixed job arguments expanding to empty string

---

src/shell/job.rs
src/shell/pipe.rs

- Standard streams are now represented as `File`s instead of `RawFd`s for `RefinedJob::Builtin`s
- Removed custom drop implementation for `RefinedJob`
**Drawbacks**: Not having a custom `Drop` implementation is nice, but now there's a lot of `unsafe { File::from_raw_fd(...) }` running about which seems like a lateral move from before.

Replace use of `RawFd` with `File` for `RefinedJob`

---

examples/builtin_piping.ion
examples/builtin_piping.out
src/shell/variables.rs
src/sys/redox.rs
src/sys/unix.rs

- Added `sys::isatty` which emulates `libc`'s `isatty`
- `read` builtin detects if `stdin` is a TTY: if so, it uses `liner`, otherwise it reads line by line assigning each new variable to each line
**Drawbacks**: If we have input like:
```
Foo
Bar
Baz
```
and call
```
$ read foo bar < input
```
The last line of input will be lost. Is this desirable? Or should we make like Bash's `read` which uses the last variable as the sink for remaining input. If so, we could make it an array of lines.
**Fixes**: Closes #474. Disclaimer: _this does not resolve all issues mentioned in the issue_ i.e.:
```
echo "foo" | read bar
```
will do nothing as `read bar` is executed in a subshell. 
**State**: Good to go barring the issue mentioned in **Drawbacks**

read builtin detects if `stdin` is a TTY

---

src/builtins/variables.rs
src/parser/loops/for_grammar.rs
src/parser/mod.rs
src/parser/pipelines/mod.rs
src/parser/shell_expand/mod.rs
src/parser/shell_expand/words.rs
src/shell/assignments.rs
src/shell/binary.rs
src/shell/flow.rs
src/shell/job.rs
src/shell/mod.rs
src/shell/variables.rs

**Problem**: `ExpanderFunctions` was somewhat unruly as:
- It was mostly used through `get_expanders!` which made tracking down errors more cumbersome as it was generated through a macro
- Hard to extend sensibly as the main instance, `get_expanders!`, would lose access to any information that was not contained within `Variables` or `DirectoryStack`
- Had weird artifacts like having a direct reference to a `Variables` but also a separate `variable(&str, bool) -> Option<Value>` function?
**Solution**: Replace `ExpanderFunctions` with an `Expander` trait which provides roughly the same interface as `ExpanderFunctions` but allows the backing implementation to be more complex 
- Removed `ExpanderFunctions`, `get_expanders!` etc.
- Add the …

Replace `ExpanderFunctions` with `Expander` trait

---

manual/src/SUMMARY.md
manual/src/ch02-00-features.md
manual/src/ch03-00-miscellaneous.md
manual/src/ch03-01-implicitcd.md
manual/src/ch05-00-expansions.md
manual/src/ch07-00-flow.md
manual/src/ch07-00-index.md

**Problem**: #499 Changed the documentation's directory structure without adapting the references within the documentation. As a result, most references to other documentation-pages were broken.
**Solution**: I updated all broken references to reflect the new directory structure.
- Fixed broken references to other documentation pages
- Added missing references to documentation pages
- Added missing link to Friendly interactive shell
- Deleted one obsolete file
**Drawbacks**: None that I know of.
**TODOs**: Nothing
**Fixes**: None
**State**: ready to merge
**Blocking/related**: #499 
**Other**: 
------
_The above template is not necessary for smaller PRs._
_It still felt good to fill it out ;-)_

Fix broken & missing links in documentation

---

examples/exists.ion
examples/exists.out
examples/glob.out
src/builtins/exists.rs
src/builtins/mod.rs
src/builtins/test.rs

**Problem**: Implement the `exists` builtin mentioned in #409 
**Solution**:
I copied over the `test` builtin implementation, removed the stuff we don't need in `exists` and implemented the necessary new logic.
- Added `exists` builtin
- Implemented the following flags: `-a`, `-b`, `-d`, `-f`, `--fn`, and `-s`
- Implemented the STRING check
- Implemented unit tests for all functions
- Implemented integration tests
**TODOs**:
- Maybe: `binary_is_in_path` should use the same logic as the one that is used to spawn new processes
- `test_binary_is_in_path` could benefit from some more unit tests, however this requires a more complex/enhanced `testing/`-directory structure
**Fixes**: #409 (partly)
**Blocking/related**: #409 …

Add "exists" builtin

---

.github/ISSUE_TEMPLATE
build.rs
src/shell/binary.rs

Adds a flag to display the version and git rev.
```
$ ion --version
ion 1.0.5 (x86_64-unknown-linux-gnu)
rev d1d02727024f98b199490122604bc8a7712c2fe4
```
`include!(concat!(env!("OUT_DIR"), "/version_string"))` might eventually be an issue if `/` isn't the default path separator though. You can't use `Path::MAIN_SEPARATOR` there.
First this tries to get the revision from `git rev-parse master` and then falls back to trying the `.git/refs/heads/master` file if the command fails. That kinda locks in the build to master branch, but I think that is OK?
(Sorry about the messy commits..)
This would close issue #515

Added a --version flag

---

manual/src/SUMMARY.md
manual/src/ch13-00-history.md
src/shell/assignments.rs
src/shell/binary.rs
src/shell/history.rs
src/shell/mod.rs

Commands that should NOT be saved in the history can be defined via the
`HISTORY_IGNORE` environment variable (array). Currently, the following
options are supported:
- `"all"`: No commands will be saved until this option is removed again
- `"whitespace"`: ignores commands with a leading whitespace character
- `"no_such_command"`: ignores commands with exit status NO_SUCH_COMMAND
- `"regex:xxx"`: where xxx is a regex (https://doc.rust-lang.org/regex), ignores all commands that match this regex
**Example**:
```
5
4
3
2
1
echo 5
echo 4
echo 3
echo 2
echo 1
echo 3
echo 2
echo 1
history | tail -5
let HISTORY_IGNORE = [ "all" ]
echo 2
echo 1
history | tail -5
let HISTORY_IGNORE = [ "all" ]
let HISTORY_IGNORE = [ "whitespace" ]
history | tail -5
let HISTORY_IGNORE = [ "all" ]
let HISTORY_IGNORE …
```

WIP: Allow user to prevent commands from being saved in history

---

rust-toolchain

Should fix AUR builds with Rustup, and clearly marks what we're targeting.
Closes #519.

rust-toolchain for latest nightly

---

src/shell/assignments.rs

The original problem I had was that when trying to compile `a6e0e86` was that I got errors such as:
```
error: expected one of `,`, `.`, `?`, or `}`, found `Err`
--> src/shell/assignments.rs:70:33
|
69 |                                 }
|                                  - expected one of `,`, `.`, `?`, or `}` here
70 |                                 Err(why) => {
|                                 ^^^ unexpected token
```
The cause of it might have been the inner `match`'s `{}` being confused for a multi-line `match` arm.
I have no idea how that slipped by, since its a syntax error. I deleted and cloned the repository again just in case; still got the same error.
Instead of simply adding `,` at the end, I decided refactor the methods to avoid such problems altogether.
This PR addresses …

refactor `match` statements

---

manual/src/ch13-00-history.md
src/shell/history.rs

In the history sub-module, only the local variables are used to determine things like the history size, whereas the documentation keeps referring to them as environment variables, which might confuse users who might attempt to export `HISTORY_SIZE` from bash for example, only to find out the changes didn't register.

distinguish between environment and local variables

---

Cargo.lock
Cargo.toml

This implements support for configuration in Redox. We can revert back after https://github.com/AndyBarron/app-dirs-rs/pull/24 is merged.

Use fork of app-dirs-rs with support for Redox

---

build.rs

Updated build.rs to require nightly. This is what has been specified in the README, so the build script should impose that check.

Update build.rs (#553) \n Nightly is required for compiling

---

src/sys/redox.rs

This makes the Redox `watch_foreground` function look much more like the Unix one. It also fixes a bug with: `something | less`

Fix Redox watch_foreground

---

src/parser/assignments/checker.rs

**Problem**: Function "is_array" returned true on input containing multiple arrays. According to part of "is_array_" test (was commented out before issue was fixed), this should not be happening.
**Solution**: Added additional check that detects the end of topmost bracket and returns false if there are characters following the end of the bracket.
- Enabled part of "is_array_" test that was previously commented out
- Added enum "IsArrayHelper"
- Altered "is_array" function
**Other**:  I am not very experienced with Rust, so this might not be ideal way to implement the check for multiple brackets.

Change to "is_array" to properly return false when multiple arrays are present

---

src/parser/pipelines/collector.rs
src/parser/pipelines/mod.rs
src/parser/statement/parse.rs
src/shell/job.rs
src/shell/mod.rs
src/shell/pipe_exec/fork.rs
src/shell/pipe_exec/mod.rs

Add multiple redirections, that is, support for things like:
```
cmd <file1 <file2 ^>> err-log > output | cmd2
```
In current ion this doesn't work.
This change at current would be breaking as the statement:
```
tr 'x' 'y' | tr 'y' 'z' < file > file2
```
redirects `file` to the first `tr` command. With this change, we would redirect it to the second.
We treat a multiple redirection as it's own job. The only difference between these jobs and normal jobs is that they only read from their source(s) and then write to their sink(s).
Alter `Pipline` contain a vector of `PipeItem`s. A `PipeItem` consists of a `Job`, a `Vec<Redirection>` and a `Vec<Input>`. The above statement would be parsed into two items, `cmd` together with `[file1, file2]` as input and `[err-log, output]` as outputs, and …

Implement mutiple redirection.

---

manual/src/ch07-01-conditionals.md

The builtin test command expects `=` for string comparisons, not `-eq`.

Fix string comparisons in documentation

---

examples/methods.ion
examples/methods.out
src/parser/shell_expand/words/methods/strings.rs

I removed some things from the template that looked like would contain duplicated answers or no answer at all.
**Problem**: Need a way to unescape strings, similar to $"\n".
**Solution**: I created two new methods, escape and unescape.
**Drawbacks**:
- The logic about how to unescape is repeated in the method and in the builtin echo. I wonder if it's possible to dedup that.
- No tests. I didn't know how to write them
**Fixes**: #556
**State**: Ready. I guess. More like: Waiting for feedback :).

Escape unescape

---

src/builtins/mod.rs
src/shell/job.rs
src/shell/mod.rs

I wasn't able to find how to run the benchmarks, if you give me instructions, I'll be happy to include them in the pr.
**Problem**: Perform lookup of builtin when parsing and not when executing, to improve for loops.
**Solution**: Perform the same logic to detect if a command is a builtin or not when creating a job and store in the struct an option for the pointer of the function of the builtin. On execution, check if that option is set to something instead of looking for the builtin.
- Add a type alias for the builtin function, `BuiltinFunction`.
- Add a new member to the job struct of type `Option<BuiltinFunction>` and name `builtin`.
- Make custom Implementations of the traits `PartialEq` and `Debug` for the job struct, since function …

Perform builtin lookup when parsing

---

Cargo.toml
examples/run_examples.sh

If you do:
```
./examples/run_examples.sh
rm src/types.rs
./examples/run_examples.sh
```
The second run will succeed even though the compilation failed. Fix this
by making the script fail if one of the steps fail.

Make ./examples/run_examples.sh fail loudly

---

src/builtins/test.rs

**Problem**: the `test` builtin is falsely passing when one of the numbers is negative.
**Solution**: Two problems were addressed:
- It was assuming that negative numbers were flag strings: Solved by checking that the second character is alphabetic.
- It was parsing to `usize`. Solved by parsing to `isize`.
Other than what commented in the solution, added tests for this cases.
**TODOs**: In the issue was commented the possibility of using `decimal` and parsing to `d128`. I didn't feel comfortable adding that overhead without a deeper discussion, so I just made the minimal fix to solve the problem.
Also... is `is_alphabetic` a good match? I felt tempted to use `is_ascii_alphabetic` instead, but it's still experimental and it wasn't considered a …

Fix test with negative numbers

---

src/parser/shell_expand/mod.rs
src/parser/shell_expand/words/methods/strings.rs

I decided to clean up some technical debt that I added in the previous commits and also add bunch of tests. 
I introduced tests for the `expand_process` function in the case of a quoted expression and tests for all the string methods. The later ones have a hidden reason: I used to make sure I understand those methods in order to write documentation about them for The Book. Because I'll use them as a reference, I'd appreciate feedback if on whether I got any wrong use case or if I'm missing one.
Also, while writing the tests, I found and fixed a bug:
```
$ echo $find("FOOBAR", "F")
0
$ echo $find("FOOBAR", "P")
0
```
To fix this, I just changed the value returned in case of `None` for a -1. Let me know if that's not what you'd expect.

Clean up some technical debt and add tests

---

examples/array_methods.ion
examples/array_methods.out
examples/run_examples.sh
src/parser/shell_expand/words/methods/arrays.rs

**Problem**: I noticed that there's no documentation for the method `split_at`. To write sensitive documentation, I like to look at the tests. For the array methods, there aren't.
**Solution**: Because there weren't, I decided to add them. As with the string methods, tests, I'll use them to update The Book later.
- e2e tests for array methods.
- Make `run_examples.sh` tell you the difference on fail.
- Unit tests for the `ArrayMethod` struct.
- Small refactor to reduce code duplication.
- Small refactor on `graphemes` to avoid cloning the structure.
**TODOs**: I have the feeling that the `split` function can slightly optimized. I'm not sure if that's worth though, I'll have to think on a way to benchmark it first.
**Fixes**: I'm very slowing …

Test and refactor of array methods

---

src/builtins/job_control.rs
src/builtins/mod.rs

**Problem**:
- disown panics if
- No arguments are provided to the command
- No jobspec's are provided to the -r or -h options
- disown does not have a help option
**Solution**:
Add a few extra checks in the implementation of `disown` and add
`disown::print_help`.
**Other:**
I hit this a few times as I was learning how to use disown.

Update the disown command

---

setup.ion

**Problem**:
When no command is provided to `setup.ion` no argument is
passed to `bad_arg` causing some errors
- Improve error handling of no options provided to the script
- Make printing help on error more ergonomic

Improve bad argument parsing of setup.ion

---

src/shell/mod.rs

During a pipeline execution, aliases are expanded and split into an
Array. The first item in this array should be either a builtin or a
command. If it is a builtin, assign the Job.builtin fn pointer field.
Otherwise, assume the alias refers to a command. Fixes #622

Allow builtins in aliases

---

build.rs

**Problem**: The word Nightly is misspelled
**Solution**: This fixes the spelling
- s/nighlty/nightly/
**Drawbacks**: None

Fixes "nighlty" typo.

---

src/shell/binary/readln.rs

**Problem**: 
Prompts containing newlines were not printing properly. The last line would print at the column of the line above it, and any lines before the last would be repeated with every keystroke.
liner runs the function for the prompt every keystroke and erases only the last line from the prompt function it's given. This leads to many trailing prompts and odd behavior in the formatting.
**Solution**: 
My solution was to remove the top lines from the prompt and present them as `prompt_info`, semantically. Then liner can print the last line of the prompt as much as it wants to.
If the prompt contains a newline the lines are printed to stdout, and the last line is supplied to the `liner` library as a prompt.
**Drawbacks**:
I'm new to the project and not sure if I handled the stdout …

Make newlines in prompt display correctly

---

Cargo.lock
Cargo.toml

~~URGENT! New users won't be able to compile ion because I accidentally deleted my fork without thinking twice.
But that is because the fork is merged, so good news too I suppose.~~
Updated rust-xdg url, they merged my fork.
EDIT: No longer urgent. Recreated the fork for now.

Update rust-xdg url in Cargo.toml

---

src/builtins/exec.rs
src/builtins/man_pages.rs
src/builtins/mod.rs
src/shell/mod.rs
src/sys/redox.rs
src/sys/unix/mod.rs

**Problem**:
The `exec` builtin does not exist
**Solution**:
Implement the `exec` builtin as a simple wrapper around the`execve` syscall.
- Add the necessary functions to builtin
- Add the necessary interfaces for the execve syscall
- Add sys::unix::execve
- Add sys::redox::execve
**TODOs**:
```
echo -e "#!/usr/bin/ion\nexec ion" > ./test.ion
ion ./test.ion
exec ion
```
**Resolution**: This occurred due to the context history not being prepped for exit.
**Fixes**:
- #608

Add the exec builtin

---

src/builtins/job_control.rs
src/builtins/mod.rs
src/builtins/variables.rs
src/shell/binary/readln.rs
src/shell/flow.rs
src/shell/mod.rs

While working in other tasks, I noticed that there's a rather
inconsistent way to handle errors. In some places we use `eprintln!` and
in others `writeln!` to standard error.
It seems like the use of `writeln!` don't have an strong motive, as the
output is always to standard error, the lock is always handled the same
than `eprintln` and there's no obvious (to me) optimization, so I
decided to use the more idiomatic `eprintln!` everywhere.
Let me know if there's seomthing I'm missing!

writeln!(stderr, ...) -> eprintln!

---

src/sys/unix/mod.rs

Found some errors with the linux implementation of `execve`
but didn't submit them in time for the merge.

Fix errors with sys::execve on linux

---

src/shell/variables/mod.rs

This change does the following:
- Adds `${USER}: ${PWD}` to the title bar using the standard xterm escape codes
- Adds a new variable type `hex` or `x` to interpret hex codes as raw characters, allowing any character to be produced as part of an `ion` variable.

Add title bar setting, add ability to produce any character using hex code

---

src/sys/redox.rs

`sys::redox::geteuid` and `sys::redox::getuid` should cast the result of
`sys::redox::cvt`, not the syscall.

Fix type casts in sys::redox

---

src/builtins/mod.rs
src/builtins/test.rs

Do not use `check_help` for parsing the help options for the `test`
builtin. The `test` builtin uses the `-h` option to check if the argument
provided is the path to a symbolic link.
Fixes: #653

Update test builtin option parsing

---

src/parser/arguments.rs

**Solution**: 
the `level: u8` variable in the `Iterator::next` implementation for the `ArgumentSplitter` was being decremented when its value was 0, causing a panic (unsigned ints cannot be less than 0).
**Changes introduced by this pull request**
i assumed that `level` represented the depth of the parentheses, so i consolidated the handling of parentheses and added `level +=1` or `level -= 1` respectively.
i also refactored the raw bit flags to use the bitflags crate for a few reason:
1) the crate was already imported
2) it makes the code a lot more readable (to me at least)
3) it helped me understand the code
**Drawbacks**
i just assumed `level` was referring to the parenthesis level, but i could be wrong. if that's the case this pull request should be rejected.

fix for issue #585

---

src/lib/shell/job.rs
src/lib/shell/mod.rs
src/lib/shell/pipe_exec/job_control.rs
src/lib/shell/pipe_exec/mod.rs
src/lib/shell/plugins/library_iter/mod.rs
src/lib/shell/plugins/mod.rs
src/lib/sys/redox.rs
src/lib/sys/unix/job_control.rs
src/lib/sys/unix/mod.rs

Job control in Ion was a complete mess, and it was a wonder that it even worked at one point to begin with! I've gone through and fixed a number of issues related to foreground job management.
- Processes are no longer preemptively killed by Ion to emulate SIGPIPE support.
- Processes within a pipeline are now assigned the same PGID.
- A SIGPIPE handler is now registered so that processes exit when they receive a SIGPIPE.
- Jobs should exit with the correct exit statuses in more situations.
- External commands now use fork + exec, rather than `std::process::Command`.
- Redox's foreground job management was also improved.
- Some refactoring was performed, with more refactoring planned in the future.
There's likely some issues that remain to be addressed though. Needs more testing & bug …

Foreground Job Control Overhaul

---

examples/methods.ion
examples/methods.out
examples/strings.ion
examples/strings.out
src/lib/parser/shell_expand/words/mod.rs

**Problem**: Fixes some weird backslash behavior
**Solution**: Changed parsing logic for backslash when in double quotes
- tests
- changes to parser logic in `words` module
**Other**
Found some weird behaviour that I tried to fix hear. Seems you already have an issue here: https://github.com/redox-os/ion/issues/640
My changes try to make it work similar to bash. I had to change one test, which I believe is wrong (`"\\n"` should convert to `"\n"`, not `"\\n"`, both bash and fish behave this way).

Fix for double quote parsing

---

Cargo.lock
Cargo.toml
examples/script_exec.ion
examples/script_exec.out
src/lib/builtins/exec.rs
src/lib/lib.rs
src/lib/shell/mod.rs
src/lib/shell/pipe_exec/job_control.rs
src/lib/shell/pipe_exec/mod.rs
src/lib/sys/redox.rs
src/lib/sys/unix/job_control.rs
src/lib/sys/unix/mod.rs

- Linux no longer requires the  **errno** crate as a dependency
- The foreground field has been removed from the shell now that it is no longer needed
- Fork + exec no longer performs allocations within child of the fork
- Added a script execution test
I'll be working on background job control next.

More Foreground Job Control Improvements

---

examples/pipelines.ion
examples/pipelines.out
src/lib/shell/mod.rs
src/lib/shell/pipe_exec/mod.rs
src/lib/sys/unix/job_control.rs
src/lib/sys/unix/mod.rs

Found some issues with pipeline execution logic, and so I've fixed them and added tests to prevent this from happening again. The following use cases are now working:
```
echo foo | grep foo && echo found foo
echo foo | grep bar || echo did not find bar
echo test | grep test && echo found test | cat
```

Pipeline Fixes & Tests

---

Cargo.lock
src/lib/sys/redox.rs

This makes the Redox waitpid usages more like the Unix ones.
We need to clean up the sys modules to make them smaller. I also added WCONTINUED, and I could implement the W* macros if desired.

Update redox-syscall, use WUNTRACED for waitpid in Redox

---

src/lib/parser/shell_expand/words/mod.rs

**Solution**:
Glob_check was incorporating one element arrays into globs and somehow consuming them. The fix simply checks if the `b']'` is not succeeded by another character, which would make it a glob pattern.
**Fixes**:
Array Parsing Issue #638

Fix to array parsing issue 

---

Cargo.lock
src/lib/lib.rs
src/lib/sys/redox/job_control.rs
src/lib/sys/redox/mod.rs

This fixes job control on Redox and makes it look more like the Unix version. This also updates the lock file, which is necessary in order to use the wif* functions on Redox.

Synchronize Redox and Unix job_control

---

setup.ion

Running `ion setup.ion build docs` failed with an error message about `09F` not being a valid color. The fix is simple, as the cause for this was only a small typo.

Fix color code in setup.ion

---

src/lib/parser/shell_expand/words/mod.rs

**Problem**:
The problem exists in tilde resolution. Only the first tilde should be expanded, But the current code expands all tildes. 
**Solution**:
My solution checks current position and only sets tilde, If current position is 0. i.e. `~` is the first character.
- Only the first tilde is resolved instead of all tildes in a string.
**Fixes**:
#709 #708 
Completed.
------

Fixed bug in tilde resolution

---

manual/src/ch14-00-history.md
src/lib/shell/variables/mod.rs

I recently reached the default HISTFILE_SIZE limit of 1000 and actually had to spend a bit of time figuring out what the problem is.
I think the current default of 1000 is much too low.
There's really no reason to constrain this to a low value as far as I can see.
I know other shells don't even disable history by default or also have very low limits, but those have historical bagge of running on very small systems.
100_000 seems much more reasonable to me.

Increase default HISTFILE_SIZE to 100000

---

src/lib/builtins/man_pages.rs
src/lib/builtins/mod.rs
src/lib/parser/statement/mod.rs
src/lib/parser/statement/parse.rs
src/lib/parser/statement/splitter.rs
src/lib/shell/flow.rs
src/lib/shell/flow_control.rs

and/or must be converted into keywords
followed suggestions in the issue discussion. Copied `Statement::Time` template

and/or followed by let results in command not found (fixes #619)

---

src/lib/parser/shell_expand/ranges.rs

**Problem**:
Descending inclusive range brace expansions calculated its limits incorrectly.
For example the expression `{20...10}` returned:
```
20 19 18 17 16 15 14 13 12
```
instead of
```
20 19 18 17 16 15 14 13 12 11 10
```
**State**:
Ready
**Other**:
The range tests in Ion are a bit lacking of edge cases, so I stress tested the fix [with this script](https://gist.github.com/xTibor/67e83e5e72d6503af4ae41b88be9523d) just to make sure I'm not introducing any regressions.

Fix descending inclusive ranges

---

src/lib/parser/pipelines/collector.rs
src/lib/parser/pipelines/mod.rs
src/lib/shell/job.rs
src/lib/shell/pipe_exec/mod.rs

Now that the statement splitter is handling this, there's no reason to leave this older logic lying around to trip on.

Remove previous and/or logic

---

src/lib/builtins/mod.rs
src/lib/parser/statement/case.rs
src/lib/shell/binary/prompt.rs
src/lib/shell/flow_control.rs
src/lib/shell/fork_function.rs
src/lib/shell/job.rs
src/lib/shell/mod.rs
src/lib/shell/pipe_exec/mod.rs

Another refactor opportunity showed up when I saw that you could just either use iterators directly without having to collect into a `Vec` allocation or just pass them between functions instead of slices when other iterators exist to again avoid said allocations.

Miscellaneous refactors

---

src/lib/builtins/mod.rs
src/lib/shell/binary/prompt.rs
src/lib/shell/flow_control.rs
src/lib/shell/fork_function.rs
src/lib/shell/job.rs
src/lib/shell/mod.rs
src/lib/shell/pipe_exec/mod.rs

This fixes a bug introduced in 9fe1eb26b72b567e71b406361133b75f8652cb97 and 23310ad61e8f26727c04863bfba126a293141ec5 while not having to allocate `Vec`s as done before those revisions by just passing `&[S]` slices everywhere, where `S: AsRef<str>`.

Fix piping issue

---

src/lib/builtins/calc.rs
src/lib/builtins/command_info.rs
src/lib/builtins/conditionals.rs
src/lib/builtins/echo.rs
src/lib/builtins/exec.rs
src/lib/builtins/exists.rs
src/lib/builtins/ion.rs
src/lib/builtins/is.rs
src/lib/builtins/job_control.rs
src/lib/builtins/man_pages.rs
src/lib/builtins/mod.rs
src/lib/builtins/random.rs
src/lib/builtins/set.rs
src/lib/builtins/source.rs
src/lib/builtins/status.rs
src/lib/builtins/test.rs
src/lib/shell/history.rs
src/lib/shell/job.rs
src/lib/shell/mod.rs
src/lib/shell/pipe_exec/mod.rs
src/lib/sys/unix/mod.rs

For the builtin functions, Ion was converting existing `&[String]` values into `Vec<&str>` by collecting each item and converting them with `as_ref()` which makes them `&str` values, to avoid from more collecting, just pass the `&[String]` borrows to save from more allocation and when a function needs to index a `&[String]` just `Deref` and borrow it.

Yet another refactor

---

src/lib/parser/statement/mod.rs
src/lib/parser/statement/splitter.rs
src/lib/shell/assignments.rs
src/lib/shell/binary/mod.rs
src/lib/shell/flow.rs
src/lib/shell/job.rs
src/lib/shell/mod.rs

This is an attempt to have `StatementSplitter` migrate back to returning `&str`s but this needs to be reviewed because this change may make ion either make you breakfast or eat your cat :stuck_out_tongue_winking_eye:

Improve StatementSplitter

---

src/lib/parser/statement/splitter.rs
src/lib/shell/mod.rs

While this doesn't solve #755, it fixes a bug where if you have an array paren expansion inside another subshell paren expansion, the statement splitter will only decrement the `p_level` and never `ap_level`.

Simplify the paren level code in StatementSplitter

---

src/lib/shell/variables/mod.rs

Support '.' characters in aliases/variables

---

Cargo.toml
src/lib/shell/binary/readln.rs
src/lib/shell/variables/mod.rs

* ansi_term 0.10.2 -> 0.11.0
* rand 0.4.2 -> 0.5.0
* users 0.6.1 -> 0.7.0
Fix building after addind in liner syntax highlight in https://github.com/redox-os/liner/pull/3

Dependency updates

---

examples/pipelines.ion
examples/pipelines.out
src/lib/parser/pipelines/collector.rs
src/lib/shell/pipe_exec/mod.rs

fixes #761 
This stops the shell hanging when given ```$(^)```, though it still seems to hang occasionally when given ```$(a | grep ^)``` which I'll look into now

Parsing bug
